version: '3.8'

services:
  flask:
    build: .
    image: flaskapp
    ports:
      - "4000:4000"
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
