CREATE TABLE events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    description TEXT,
    image VARCHAR(255),
    link VARCHAR(255)
);

INSERT INTO events (name, location, description, image, link) VALUES
    ('Ed Sheeran Concert', 'Principality Stadium', 'Ed Sheeran live at Principality Stadium', 'https://images.sk-static.com/images/media/profile_images/artists/2083334/huge_avatar', 'https://www.principalitystadium.wales/'),
    ('Coldplay Live', 'Wembley Stadium', 'Coldplay performing live at Wembley Stadium', 'https://images.sk-static.com/images/media/profile_images/artists/287767/huge_avatar', 'https://www.wembleystadium.com/'),
    ('Coachella Festival', 'Indio, California', 'Annual music and arts festival in Indio, California', 'https://images.sk-static.com/images/media/profile_images/artists/3283933/huge_avatar', 'https://www.coachella.com/'),
    ('Lollapalooza', 'Grant Park, Chicago', 'Annual music festival featuring popular artists', 'https://images.sk-static.com/images/media/profile_images/artists/213260/huge_avatar', 'https://www.lollapalooza.com/'),
    ('Glastonbury Festival', 'Worthy Farm, Somerset', 'One of the largest greenfield music and performing arts festivals in the world', 'https://images.sk-static.com/images/media/profile_images/artists/3743695/huge_avatar', 'https://www.glastonburyfestivals.co.uk/'),
    ('Tomorrowland', 'Boom, Belgium', 'Electronic dance music festival held in Boom, Belgium', 'https://images.sk-static.com/images/media/profile_images/artists/271944/huge_avatar', 'https://www.tomorrowland.com/'),
    ('Reading Festival', 'Reading, UK', 'Annual rock music festival held at Richfield Avenue in Reading, UK', 'https://images.sk-static.com/images/media/profile_images/artists/282090/huge_avatar', 'https://www.readingfestival.com/'),
    ('Leeds Festival', 'Leeds, UK', 'Annual music and arts festival taking place at Bramham Park in Leeds, UK', 'https://images.sk-static.com/images/media/profile_images/artists/282090/huge_avatar', 'https://www.leedsfestival.com/'),
    ('Bonnaroo Music Festival', 'Manchester, Tennessee', 'Annual music and arts festival held at Great Stage Park in Manchester, Tennessee', 'https://images.sk-static.com/images/media/profile_images/artists/282294/huge_avatar', 'https://www.bonnaroo.com/'),
    ('SXSW Festival', 'Austin, Texas', 'Annual conglomerate of film, interactive media, and music festivals and conferences', 'https://images.sk-static.com/images/media/profile_images/artists/282283/huge_avatar', 'https://www.sxsw.com/'),
    ('Roskilde Festival', 'Roskilde, Denmark', 'Annual music festival in Denmark', 'https://images.sk-static.com/images/media/profile_images/artists/282110/huge_avatar', 'https://www.roskilde-festival.dk/'),
    ('Electric Daisy Carnival', 'Las Vegas, Nevada', 'Electronic dance music and art festival', 'https://images.sk-static.com/images/media/profile_images/artists/282279/huge_avatar', 'https://lasvegas.electricdaisycarnival.com/'),
    ('Primavera Sound', 'Barcelona, Spain', 'Annual music festival in Barcelona, Spain', 'https://images.sk-static.com/images/media/profile_images/artists/282233/huge_avatar', 'https://www.primaverasound.com/'),
    ('Sziget Festival', 'Budapest, Hungary', 'Annual music and cultural festival in Budapest, Hungary', 'https://images.sk-static.com/images/media/profile_images/artists/282180/huge_avatar', 'https://szigetfestival.com/'),
    ('Ultra Music Festival', 'Miami, Florida', 'Annual electronic music festival in Miami, Florida', 'https://images.sk-static.com/images/media/profile_images/artists/282300/huge_avatar', 'https://www.ultramusicfestival.com/'),
    ('Osheaga Festival', 'Montreal, Canada', 'Annual music and arts festival in Montreal, Canada', 'https://images.sk-static.com/images/media/profile_images/artists/282147/huge_avatar', 'https://www.osheaga.com/'),
    ('Outside Lands Music Festival', 'San Francisco, California', 'Annual music festival in San Francisco, California', 'https://images.sk-static.com/images/media/profile_images/artists/282176/huge_avatar', 'https://www.sfoutsidelands.com/'),
    ('Wireless Festival', 'London, UK', 'Annual music festival in London, UK', 'https://images.sk-static.com/images/media/profile_images/artists/282292/huge_avatar', 'https://www.wirelessfestival.co.uk/'),
    ('Electric Zoo Festival', 'New York City, New York', 'Electronic music festival held annually in New York City', 'https://images.sk-static.com/images/media/profile_images/artists/282274/huge_avatar', 'https://electriczoo.com/'),
    ('Mawazine Festival', 'Rabat, Morocco', 'Annual music festival in Rabat, Morocco', 'https://images.sk-static.com/images/media/profile_images/artists/282142/huge_avatar', 'https://www.festivalmawazine.ma/'),
    ('Rock am Ring', 'Nürburg, Germany', 'Rock music festival in Germany', 'https://images.sk-static.com/images/media/profile_images/artists/282160/huge_avatar', 'https://www.rock-am-ring.com/'),
    ('Rock im Park', 'Nuremberg, Germany', 'Rock music festival in Germany', 'https://images.sk-static.com/images/media/profile_images/artists/282161/huge_avatar', 'https://www.rock-im-park.com/'),
    ('Download Festival', 'Donington Park, UK', 'Rock and metal music festival', 'https://images.sk-static.com/images/media/profile_images/artists/282297/huge_avatar', 'https://downloadfestival.co.uk/'),
    ('Firefly Music Festival', 'Dover, Delaware', 'Annual music festival in the United States', 'https://images.sk-static.com/images/media/profile_images/artists/282304/huge_avatar', 'https://www.fireflyfestival.com/'),
    ('Arenal Sound', 'Burriana, Spain', 'Annual music festival held in Burriana, Spain', 'https://images.sk-static.com/images/media/profile_images/artists/282236/huge_avatar', 'https://www.arenalsound.com/'),
    ('Mad Cool Festival', 'Madrid, Spain', 'Annual music festival in Madrid, Spain', 'https://images.sk-static.com/images/media/profile_images/artists/282279/huge_avatar', 'https://www.madcoolfestival.es/'),
    ('FIB Benicàssim', 'Benicàssim, Spain', 'Annual music festival in Benicàssim, Spain', 'https://images.sk-static.com/images/media/profile_images/artists/282150/huge_avatar', 'https://fiberfib.com/'),
    ('Wireless Germany', 'Frankfurt, Germany', 'Annual music festival in Germany', 'https://images.sk-static.com/images/media/profile_images/artists/282148/huge_avatar', 'https://www.wireless-festival.de/'),
    ('Longitude Festival', 'Dublin, Ireland', 'Annual music festival in Dublin, Ireland', 'https://images.sk-static.com/images/media/profile_images/artists/282147/huge_avatar', 'https://longitude.ie/'),
    ('Bestival', 'Isle of Wight, UK', 'Annual music festival on the Isle of Wight', 'https://images.sk-static.com/images/media/profile_images/artists/282276/huge_avatar', 'https://www.bestival.net/'),
    ('Parklife Festival', 'Manchester, UK', 'Annual music festival in Manchester, UK', 'https://images.sk-static.com/images/media/profile_images/artists/282170/huge_avatar', 'https://parklife.uk.com/'),
    ('Lovebox Festival', 'London, UK', 'Annual music festival in London, UK', 'https://images.sk-static.com/images/media/profile_images/artists/282269/huge_avatar', 'https://loveboxfestival.com/'),
    ('Creamfields', 'Daresbury, UK', 'Annual dance music festival in the UK', 'https://images.sk-static.com/images/media/profile_images/artists/282292/huge_avatar', 'https://www.creamfields.com/'),
    ('Latitude Festival', 'Suffolk, UK', 'Annual music and performing arts festival in Suffolk, UK', 'https://images.sk-static.com/images/media/profile_images/artists/282265/huge_avatar', 'https://www.latitudefestival.com/'),
    ('End of the Road Festival', 'Larmer Tree Gardens, UK', 'Annual music festival in the UK', 'https://images.sk-static.com/images/media/profile_images/artists/282301/huge_avatar', 'https://endoftheroadfestival.com/');
